[mysql]
host="127.0.0.1:3306"
user="root"
password="123456"
dbname="deal"

[redis]
host="127.0.0.1:6379"
password=""
db=0
poolsize=100

[log]
levels=[{ name = "inited", level = "info" },{ name = "handler", level = "debug" }]
